import streamlit as st
import torch
import io
import soundfile as sf
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# 1. App Window Initialization
st.set_page_config(page_title="Runyankole Neural App", layout="centered")
st.title("🇺🇬 True Runyankole AI Translator")
st.markdown("---")


# 2. Optimized Pipeline / Engine Caching
@st.cache_resource
def load_speech_models():
    return pipeline("automatic-speech-recognition", model="openai/whisper-tiny")


@st.cache_resource
def load_translation_engine():
    # Utilizing the globally stable core architecture checkpoint
    model_name = "facebook/nllb-200-distilled-600M"
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    
    return tokenizer, model, device


# Instantiate Models
asr_pipeline = load_speech_models()
tokenizer, translation_model, device = load_translation_engine()

# Standard BCP-47 Target Codes utilized by Meta NLLB-200
language_tokens = {
    'eng': 'eng_Latn', 
    'nyn': 'nyn_Latn'
}

def translate_via_neural_net(text, direction_mode):
    try:
        if direction_mode == "English to Runyankole":
            src_lang = language_tokens['eng']
            tgt_lang = language_tokens['nyn']
        else:
            src_lang = language_tokens['nyn']
            tgt_lang = language_tokens['eng']

        # Set the source language token state directly onto the tokenizer object instance
        tokenizer.src_lang = src_lang

        # Tokenize the input phrase safely into tensor sequences
        inputs = tokenizer(text, return_tensors="pt").to(device)

        # Extract the target vocabulary token identifier mapping 
        forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)

        # Generate translation matrix passing explicit structural parameters
        translated_tokens = translation_model.generate(
            **inputs,
            forced_bos_token_id=forced_bos_token_id,
            max_length=256,
            num_beams=4,      # Increased to 4 for optimal context decoding search
            do_sample=False   
        )

        # FIX: Correctly decode and extract index [0] to fetch the pure string
        result = tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)
        if isinstance(result, list) and len(result) > 0:
            return result[0]  # <--- FIXED: Safely returns string sentence instead of whole array list
        return "No output generated by neural framework."
        
    except Exception as e:
        return f"Translation Subsystem Error Trace: {str(e)}"


# 3. Mode Configuration UI
direction = st.sidebar.selectbox("Flow Mode:", ["English to Runyankole", "Runyankole to English"])

# Initialize session state tracking spaces
if "voice_text" not in st.session_state:
    st.session_state.voice_text = "I love you so much"
if "last_processed_audio" not in st.session_state:
    st.session_state.last_processed_audio = None

# 4. Audio Processing Workflow Block
recorded_audio = st.audio_input("Record voice input")

# Only run transcription if the audio object is completely new
if recorded_audio is not None and recorded_audio != st.session_state.last_processed_audio:
    with st.spinner("Processing speech audio layer..."):
        try:
            audio_bytes = recorded_audio.read()
            audio_data, sample_rate = sf.read(io.BytesIO(audio_bytes))
            if len(audio_data.shape) > 1:
                audio_data = audio_data[:, 0]
            
            result = asr_pipeline({"raw": audio_data, "sampling_rate": sample_rate})
            
            st.session_state.voice_text = result["text"]
            st.session_state.last_processed_audio = recorded_audio
            st.rerun() 
        except Exception as e:
            st.error(f"Audio Decode Error: {e}")

if recorded_audio is None:
    st.session_state.last_processed_audio = None

# 5. Direct State Binding Layout
sentence = st.text_input("Input Phrase:", key="voice_text")
submit_button = st.button(label="Translate Text", type="primary")

# Execute conversion on button confirmation state matching
if submit_button and sentence:
    with st.spinner("Running Neural Net Inference..."):
        output_translation = translate_via_neural_net(sentence, direction)
        st.subheader("Neural Network Result:")
        st.success(output_translation)
