import streamlit as st
import torch
import io
import soundfile as sf
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# 1. App Window Initialization
st.set_page_config(page_title="Runyankole Neural App", layout="centered")
st.title("🇺🇬 True Runyankole AI Translator")
st.markdown("---")

# 2. Optimized Pipeline / Engine Caching
@st.cache_resource
def load_speech_models():
    # Forced to CPU/GPU map cleanly
    device = 0 if torch.cuda.is_available() else -1
    return pipeline("automatic-speech-recognition", model="openai/whisper-tiny", device=device)

@st.cache_resource
def load_translation_engine():
    model_name = "facebook/nllb-200-distilled-600M"
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    # low_cpu_mem_usage prevents RAM spikes during load phase
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name, low_cpu_mem_usage=True)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    
    return tokenizer, model, device

# Instantiate Models Safely
asr_pipeline = load_speech_models()
tokenizer, translation_model, device = load_translation_engine()

language_tokens = {
    'eng': 'eng_Latn', 
    'nyn': 'nyn_Latn'
}

def translate_via_neural_net(text, direction_mode):
    try:
        if direction_mode == "English to Runyankole":
            src_lang = language_tokens['eng']
            tgt_lang = language_tokens['nyn']
        else:
            src_lang = language_tokens['nyn']
            tgt_lang = language_tokens['eng']

        tokenizer.src_lang = src_lang
        inputs = tokenizer(text, return_tensors="pt").to(device)
        forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)

        # CRITICAL FIX: Wrapped in torch.no_grad() to stop memory accumulation leaks
        with torch.no_grad():
            translated_tokens = translation_model.generate(
                **inputs,
                forced_bos_token_id=forced_bos_token_id,
                max_length=128,    # Reduced from 256 to speed up CPU inference
                num_beams=2,       # Reduced from 4 to prevent CPU execution freezing
                do_sample=False   
            )

        result = tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)
        if isinstance(result, list) and len(result) > 0:
            return result[0] 
        return "No output generated by neural framework."
        
    except Exception as e:
        return f"Translation Subsystem Error Trace: {str(e)}"


# 3. Mode Configuration UI
direction = st.sidebar.selectbox("Flow Mode:", ["English to Runyankole", "Runyankole to English"])

# Initialize session state safely without cross-binding pollution
if "text_placeholder" not in st.session_state:
    st.session_state.text_placeholder = "I love you so much"

# 4. Audio Processing Workflow Block
recorded_audio = st.audio_input("Record voice input")

if recorded_audio is not None:
    try:
        audio_bytes = recorded_audio.read()
        audio_data, sample_rate = sf.read(io.BytesIO(audio_bytes))
        if len(audio_data.shape) > 1:
            audio_data = audio_data[:, 0]
        
        # Calculate a simple hash to see if the file changed instead of st.rerun loop
        audio_hash = hash(audio_bytes)
        if "last_audio_hash" not in st.session_state or st.session_state.last_audio_hash != audio_hash:
            with st.spinner("Processing speech audio layer..."):
                result = asr_pipeline({"raw": audio_data, "sampling_rate": sample_rate})
                st.session_state.text_placeholder = result["text"]
                st.session_state.last_audio_hash = audio_hash
                st.rerun() # Clean rerun now that hash safeguards it
    except Exception as e:
        st.error(f"Audio Decode Error: {e}")

# 5. Direct State Binding Layout using a Form to stop element freezing
with st.form("translation_form"):
    sentence = st.text_input("Input Phrase:", value=st.session_state.text_placeholder)
    submit_button = st.form_submit_button(label="Translate Text", type="primary")

# Execute conversion on form submission block explicitly
if submit_button and sentence:
    with st.spinner("Running Neural Net Inference..."):
        output_translation = translate_via_neural_net(sentence, direction)
        st.subheader("Neural Network Result:")
        st.success(output_translation)
